### ISSUE TITLE
Various ways of sending an "empty message" crashes the bot

### ISSUE THREAD

**Issue by RinaBTW** [Senither/hypixel-discord-chat-bridge#21]
For example just sending an @ sign will crash it

**Comment by Senither** [comment]
The bot appears to work fine when sending just `@` as a message, are you using the latest version of the bot?

![https://alexis.is-just-a-me.me/i/AWorkableOldPrint](https://alexis.is-just-a-me.me/i/AWorkableOldPrint)

On another note, the software I'm using in the screenshot is called [PM2](https://pm2.keymetrics.io/), I highly recommend you use that to run the bot if you're not already using it, it will automatically restart the bot in case it crashes or fails for any reason, just makes all sorts of NodeJS processes easier to manage.

**Comment by RinaBTW** [comment]
Thank you for the PM2 suggestion it's very useful, it doesn't crash while using that. It does, however, still throw an error when trying to send just "@" from in-game to Discord. I'm also in webhook mode if that helps. Everything is updated.
![image](https://user-images.githubusercontent.com/84283903/121017150-f40ebf00-c76a-11eb-9a3b-f7bc4b8a92a3.png)

**Comment by Senither** [comment]
From the error it looks like the issue stems from trying to send a webhook request with no actual message content(Since the bot strips out some special characters, such as `@` that is used by Discord), I'll look into making a fix for it when I get home so it doesn't happen in the future, thanks for reporting the issue^^
