### ISSUE TITLE
OwnerID Cannot be role

### ISSUE THREAD

**Issue by DuckySoLucky** [Senither/hypixel-discord-chat-bridge#38]
Heya, so only 1 person can use !override is OwnerID, I tried using role but it doesnt work. Can someone tell me why? And how to make it? Its not really an issue but still You guys should maek ability to toggle it to role and to only 1 user :/

**Comment by Senither** [comment]
User IDs and role IDs are handled completely differently in Discord which is why you can't just substitute a role ID for a user ID, the idea for the override command is for it to only be accessible by a single person, the person hosting the bot most likely, there isn't really any plans to make it usable by more people, if other people need to do something through the bot they can use the other commands made specifically for that which does have a role ID check before they can be used.
